syntax = "proto3";

package domain;

import "achievements.proto";
import "authenticator.proto";
import "credential_service.proto";
import "google/protobuf/timestamp.proto";
import "google/protobuf/wrappers.proto";
import "organization_type.proto";
import "profile.proto";
import "profile_type.proto";
import "registration_info_status.proto";
import "sync_update.proto";
import "vault_service.proto";
import "webauthn_prf_support_status.proto";

option go_package = "gitlab.com/cotechde/monorepo/backend/domain/pb";

message GetRegistrationInfoRequest {
  string email = 1;
  string profile_id = 2;
}

message GetRegistrationInfoResponse {
  message Organization {
    string name = 1;
    string icon = 2;
    string id = 3;
    string profile_id = 4;
    string start_code_prefix = 5;
    OrganizationType organization_type = 6;
  }

  RegistrationInfoStatus status = 1;
  GetRegistrationInfoResponse.Organization organization = 2;
  bool webauthn_allowed = 3;
  ProfileType profile_type = 7;
  reserved 4;
  reserved 5;
}

message CreateAccountWithProfileRequest {
  message WebauthnCredentialData {
    string request_id = 1;
    string response_json = 2;
    WebauthnPrfSupportStatus prf_support_status = 3;
  }

  message SessionUnlockData {
    bytes encrypted_secret = 1;
    google.protobuf.Timestamp unlock_max_expires_at = 2;
  }

  repeated AuthenticatorCreationData authenticators = 14;
  ProfileData preferences_profile = 2;
  ProfileData inbox_profile = 3;
  VaultCreationData meta_vault = 4;
  string referrer_id = 5;
  bytes authenticator_block = 6;
  bytes authenticator_block_signature = 7;
  string preliminary_email = 10;
  string start_code = 13;
  CreateAccountWithProfileRequest.SessionUnlockData session_unlock_data = 15;
  CreateAccountWithProfileRequest.WebauthnCredentialData webauthn_credential_data = 16;
  string start_code_profile_id = 17;
  reserved 1;
  reserved 8;
  reserved 9;
}

message CreateAccountWithProfileResponse {
  string user_id = 1;
  Token access_token = 2;
  string session_id = 3;
  repeated string authenticator_ids = 4;
  string preferences_profile_id = 5;
  string meta_vault_id = 7;
  string inbox_profile_id = 6;
  int32 token_version = 8;
}

message UpdateAccountRequest {
  google.protobuf.StringValue preferred_locale = 2;
  google.protobuf.StringValue user_client_settings = 3;
  google.protobuf.BoolValue profiles_locked = 4;
  reserved 1;
}

message UpdateAccountResponse {
  SyncUpdate sync_update = 1;
}

message CreateReferrerRequest {
  string referrer = 1;
}

message CreateReferrerResponse {
  string referrer_id = 1;
}

message AddAchievementsRequest {
  repeated Achievement achievements = 1;
}

message AddAchievementsResponse {
  SyncUpdate sync_update = 1;
}

message ListAccountsRequest {
  message User {
    string id = 1;
    bytes authenticator_block_hash = 2;
  }

  repeated ListAccountsRequest.User users = 1;
  repeated string emails = 2;
  repeated string profile_ids = 3;
}

message ListAccountsResponse {
  message User {
    message ForeignAuthenticator {
      string id = 1;
      bytes high_security_identity_sig_pub_key = 3;
      bytes high_security_profile_seed_enc_pub_key = 4;
      bytes high_security_profile_seed_enc_pub_key_signature = 5;
      bytes storable_sig_pub_key = 6;
      bytes storable_sig_pub_key_signature = 7;
      bytes storable_profile_seed_enc_pub_key = 8;
      bytes storable_profile_seed_enc_pub_key_signature = 9;
    }

    string user_id = 1;
    string email = 2;
    repeated ListAccountsResponse.User.ForeignAuthenticator authenticators = 3;
    repeated AuthenticatorBlock authenticator_blocks = 4;
    reserved 5;
  }

  repeated ListAccountsResponse.User users = 1;
}

message ResolveEmailsRequest {
  repeated string emails = 1;
  bool fail_fast = 2;
}

message ResolveEmailsResponse {
  message ResolvedProfile {
    string id = 1;
    string organization_id = 2;
    ProfileType profile_type = 3;
  }

  message ResolvedEmail {
    string email = 1;
    bool email_invalid = 4;
    repeated ResolveEmailsResponse.ResolvedProfile profiles = 2;
    string user_id = 3;
  }

  repeated ResolveEmailsResponse.ResolvedEmail emails = 1;
}

message GetPaddleConfigRequest {
}

message GetPaddleConfigResponse {
  bool is_sandbox = 1;
  string wrapper_host = 2;
  int64 vendor_id = 3;
  int64 product_id_monthly = 4;
  int64 product_id_yearly = 5;
}

message DeleteAccountRequest {
}

message DeleteAccountResponse {
}

service AccountService {
  rpc GetRegistrationInfo(GetRegistrationInfoRequest) returns (GetRegistrationInfoResponse) {}
  rpc CreateWithProfile(CreateAccountWithProfileRequest) returns (CreateAccountWithProfileResponse) {}
  rpc Update(UpdateAccountRequest) returns (UpdateAccountResponse) {}
  rpc CreateReferrer(CreateReferrerRequest) returns (CreateReferrerResponse) {}
  rpc AddAchievements(AddAchievementsRequest) returns (AddAchievementsResponse) {}
  rpc List(ListAccountsRequest) returns (ListAccountsResponse) {}
  rpc ResolveEmails(ResolveEmailsRequest) returns (ResolveEmailsResponse) {}
  rpc GetPaddleConfig(GetPaddleConfigRequest) returns (GetPaddleConfigResponse) {}
  rpc Delete(DeleteAccountRequest) returns (DeleteAccountResponse) {}
}

