syntax = "proto3";

package domain;

option java_package = "app.heylogin.android.proto";
option go_package = "gitlab.com/cotechde/monorepo/backend/domain/pb";
option objc_class_prefix = "HPA";

enum Achievement {
  UNKNOWN = 0;
  BAE_REGISTER_ANDROID = 1;
  BAE_REGISTER_IOS = 2;
  BAE_REGISTER_WEB = 11;
  BAE_REGISTER_BAK = 12;
  BAE_INACTIVE_MARKED_FOR_DELETION = 3;
  BAE_REACTIVATED = 4;
  BAE_ORG_ICON_FOUND = 5;
  BAE_LOGIN_RECOVERY = 6;
  BAE_LOGIN_BACKUP = 7;
  BAE_PRIVATE_PROFILE_DELETE = 8;
  BAE_LOGIN_INBOX_CREATE = 9;
  BAE_LOGIN_INBOX_MESSAGE = 10;
  AND_AUTOFILL_SETUP = 1000000;
  AND_AUTOFILL_ENABLE = 1000001;
  AND_AUTOFILL_INSERT = 1000002;
  AND_AUTOFILL_UPDATE = 1000003;
  AND_BACKUP_REGULAR = 1000100;
  AND_BACKUP_E2E = 1000101;
  AND_BACKUP_TRANSFER = 1000102;
  AND_REVIEW_CONDITIONS_FULFILLED = 1000200;
  AND_REVIEW_SHOWN = 1000201;
  AND_REVIEW_STAYED_3_SECONDS = 1000202;
  AND_SCAN_CAMERA_REQUESTED = 1000300;
  AND_SCAN_CAMERA_GRANTED = 1000301;
  AND_SCAN_SCANNED = 1000302;
  AND_SCAN_FROM_EXTERNAL = 1000303;
  AND_KEYSTORE_LOST_SHOWN_NO_BACKUP = 1000400;
  AND_KEYSTORE_LOST_SHOWN_BACKUP_AVAILABLE = 1000401;
  AND_SECOND_FACTOR_ENFORCEMENT_GRANDFATHERED = 1000500 [deprecated = true];
  AND_INSTALLED_VIA_ADMIN_POLICY = 1000600 [deprecated = true];
  AND_HAS_RESTRICTIONS_PROVIDER = 1000601 [deprecated = true];
  WEB_SESSION_CREATE = 2000000;
  WEB_SESSION_UNLOCK = 2000001;
  WEB_SESSION_PHONE = 2000010;
  WEB_SESSION_TABLET = 2000011;
  WEB_IMPORT_HEYLOGIN = 2000100;
  WEB_IMPORT_BITWARDEN = 2000101;
  WEB_IMPORT_LASTPASS = 2000102;
  WEB_IMPORT_CHROME = 2000103;
  WEB_IMPORT_FIREFOX = 2000104;
  WEB_IMPORT_DASHLANE = 2000105;
  WEB_IMPORT_ONEPASSWORD = 2000106;
  WEB_IMPORT_KEEPASS = 2000107;
  WEB_IMPORT_SAFARI = 2000108;
  WEB_IMPORT_NORDPASS = 2000109;
  WEB_IMPORT_STICKYPASSWORD = 2000110;
  WEB_IMPORT_CSV = 2000111;
  WEB_IMPORT_EXCEL = 2000112;
  WEB_IMPORT_ENPASS = 2000113;
  WEB_IMPORT_PROTONPASS = 2000114;
  WEB_IMPORT_KEEPER = 2000115;
  WEB_EXPORT = 2000200;
  WEB_LOGIN_ADD = 2000300;
  WEB_LOGIN_ADD_FIRST_MANUAL = 2000301;
  WEB_USE_SEARCH_SHORTCUT = 2000302;
  WEB_LOGIN_CREATE_SHARE_LINK = 2000303;
  WEB_PADDLE_SUBSCRIBE_OPENED = 2000400;
  WEB_PADDLE_SUBSCRIBE_CLOSED = 2000401;
  WEB_PADDLE_SUBSCRIBE_COMPLETED = 2000402;
  WEB_PADDLE_MANAGE_OPENED = 2000420;
  WEB_PADDLE_MANAGE_CLOSED = 2000421;
  WEB_PADDLE_MANAGE_COMPLETED = 2000422;
  WEB_ORGANIZATION_CREATE = 2000500;
  WEB_ORGANIZATION_JOIN = 2000501;
  WEB_ORGANIZATION_ADMIN_ACCESS_PERSONAL = 2000502;
  WEB_ORGANIZATION_USER_ADD_EXISTING = 2000510;
  WEB_ORGANIZATION_USER_REMOVE_EXISTING = 2000511;
  WEB_ORGANIZATION_USER_ADD_NEW = 2000512;
  WEB_ORGANIZATION_USER_REMOVE_NEW = 2000513;
  WEB_ORGANIZATION_USER_CHANGE_ACCESS_LEVEL = 2000514;
  WEB_ORGANIZATION_TEAM_CREATE = 2000520;
  EXT_INSTALL = 3000000;
  EXT_DISABLE_FOR_PAGE = 3000001;
  EXT_REPORT_PAGE = 3000002;
  EXT_LOGIN_INSERT = 3000100;
  EXT_LOGIN_UPDATE = 3000101;
  EXT_AUTOSNATCH_FROM_LOGIN = 3000110;
  EXT_AUTOSNATCH_FROM_REGISTRATION = 3000111 [deprecated = true];
  EXT_OVERLAY_LOGIN = 3000200;
  EXT_OVERLAY_UNLOCK = 3000201;
  EXT_OVERLAY_NEW_LOGIN = 3000202 [deprecated = true];
  EXT_OVERLAY_NEW_LOGIN_FROM_PENDING_REGISTRATION = 3000203 [deprecated = true];
  EXT_OVERLAY_UPDATE_GENERATED_PASSWORD = 3000204;
  EXT_OVERLAY_DISABLE_AUTOSNATCH = 3000004;
  EXT_OVERLAY_SAW_NAG_SCREEN = 3000005;
  EXT_POPUP_OPEN = 3000300;
  EXT_POPUP_UNLOCK = 3000301;
  EXT_POPUP_DISABLE_AUTOSNATCH = 3000003;
  EXT_OMNIBOX_INPUT_CHANGED = 3000400;
  EXT_OMNIBOX_INPUT_ENTERED = 3000401;
  EXT_CONTEXT_MENU_HEYLOGIN_ENABLED = 3000500;
  EXT_CONTEXT_MENU_USERNAME_FILLED = 3000510;
  EXT_CONTEXT_MENU_PASSWORD_FILLED = 3000511;
  EXT_CONTEXT_MENU_CUSTOM_TOTP_FILLED = 3000512;
  EXT_CONTEXT_MENU_CUSTOM_PLAIN_FILLED = 3000513;
  EXT_CONTEXT_MENU_CUSTOM_PROTECTED_FILLED = 3000514;
  EXT_GLOBAL_SEARCH_OPEN = 3000600;
  EXT_GLOBAL_SEARCH_UNLOCK = 3000601;
  EXT_LEGACY_AUTOTYPE_INSTALLED = 3000700;
  EXT_AUTOTYPE_INSTALLED = 3000701;
  EXT_AUTOTYPE_USED_ACCELERATOR = 3000702;
  EXT_FULLSCREEN_OVERLAY_OPEN = 3000800;
  EXT_FULLSCREEN_OVERLAY_UNLOCK = 3000801;
  EXT_PASSKEY_GET_OVERLAY_OPEN = 3000900;
  EXT_PASSKEY_GET_OVERLAY_CANCEL = 3000901;
  EXT_PASSKEY_GET_OVERLAY_USE_SECURITY_KEY = 3000902;
  EXT_PASSKEY_GET_OVERLAY_ALREADY_OPEN = 3000904;
  EXT_PASSKEY_GET_OVERLAY_UNLOCK = 3000905;
  EXT_PASSKEY_CREATE_OVERLAY_OPEN = 3000910;
  EXT_PASSKEY_CREATE_OVERLAY_CANCEL = 3000911;
  EXT_PASSKEY_CREATE_OVERLAY_USE_SECURITY_KEY = 3000912;
  EXT_PASSKEY_CREATE_OVERLAY_SHOW_ERROR = 3000913;
  EXT_PASSKEY_CREATE_OVERLAY_ALREADY_OPEN = 3000914;
  EXT_PASSKEY_CREATE_OVERLAY_UNLOCK = 3000915;
  EXT_PASSKEY_CREATE = 3000920;
  EXT_PASSKEY_CREATE_EC = 3000921;
  EXT_PASSKEY_CREATE_RSA = 3000922;
  EXT_PASSKEY_CREATE_OKP = 3000923;
  EXT_PASSKEY_GET = 3000930;
  EXT_PASSKEY_GET_EC = 3000931;
  EXT_PASSKEY_GET_RSA = 3000932;
  EXT_PASSKEY_GET_OKP = 3000933;
  EXT_PASSKEY_GET_REQUEST = 3000940;
  EXT_PASSKEY_CREATE_REQUEST = 3000941;
  EXT_PASSKEY_GET_REQUEST_MEDIATION_CONDITIONAL = 3000950;
  EXT_PASSKEY_GET_REQUEST_MEDIATION_SILENT = 3000951;
  EXT_PASSKEY_GET_REQUEST_MEDIATION_OPTIONAL = 3000952;
  EXT_PASSKEY_GET_REQUEST_MEDIATION_REQUIRED = 3000953;
  EXT_PASSKEY_GET_REQUEST_REJECT_FAILED_DOMAIN_SUFFIX = 3000954;
  EXT_PASSKEY_GET_REQUEST_REJECT_CONCURRENT_OPERATION = 3000955;
  EXT_PASSKEY_GET_REQUEST_PARSE_ERROR = 3000956;
  EXT_PASSKEY_GET_REQUEST_ABORT = 3000957;
  EXT_PASSKEY_CREATE_REQUEST_MEDIATION_CONDITIONAL = 3000960;
  EXT_PASSKEY_CREATE_REQUEST_MEDIATION_SILENT = 3000961;
  EXT_PASSKEY_CREATE_REQUEST_MEDIATION_OPTIONAL = 3000962;
  EXT_PASSKEY_CREATE_REQUEST_MEDIATION_REQUIRED = 3000963;
  EXT_PASSKEY_CREATE_REQUEST_REJECT_FAILED_DOMAIN_SUFFIX = 3000964;
  EXT_PASSKEY_CREATE_REQUEST_REJECT_CONCURRENT_OPERATION = 3000965;
  EXT_PASSKEY_CREATE_REQUEST_PARSE_ERROR = 3000966;
  EXT_PASSKEY_CREATE_REQUEST_ABORT = 3000967;
  EXT_PASSKEY_GET_MEDIATION_CONDITIONAL = 3000970;
  EXT_PASSKEY_GET_MEDIATION_OPTIONAL = 3000972;
  EXT_PASSKEY_GET_MEDIATION_REQUIRED = 3000973;
  EXT_PASSKEY_CREATE_MEDIATION_CONDITIONAL = 3000980;
  EXT_PASSKEY_CREATE_MEDIATION_OPTIONAL = 3000982;
  EXT_PASSKEY_CREATE_MEDIATION_REQUIRED = 3000983;
  COR_LOGINS_TOTAL_1 = 4000000;
  COR_LOGINS_TOTAL_2 = 4000001;
  COR_LOGINS_TOTAL_4 = 4000002;
  COR_LOGINS_TOTAL_8 = 4000003;
  COR_LOGINS_TOTAL_16 = 4000004;
  COR_LOGINS_TOTAL_32 = 4000005;
  COR_LOGINS_TOTAL_64 = 4000006;
  COR_LOGINS_TOTAL_128 = 4000007;
  COR_LOGINS_TOTAL_256 = 4000008;
  COR_LOGINS_TOTAL_512 = 4000009;
  COR_LOGINS_TOTAL_1024 = 4000010;
  COR_STORE_BACKUP_CODE_META_VAULT = 4000011;
  COR_LINKED_LOGIN_CREATE_PERSONAL = 4000012;
  COR_LINKED_LOGIN_CREATE_TEAM = 4000013;
  COR_ADD_GEO_UNLOCK_REGION = 4000014 [deprecated = true];
  COR_LOGIN_CREATE_SHARE_SECRET = 4000304;
  IOS_AUTOFILL_GUIDE_SETUP = 5000000;
  IOS_AUTOFILL_ENABLE = 5000001;
  IOS_SECOND_FACTOR_ENFORCEMENT_GRANDFATHERED = 5000100;
  CNB_IMPORT_CXF = 6000100;
}

