syntax = "proto3";

package domain;

option java_package = "app.heylogin.android.proto";
option go_package = "gitlab.com/cotechde/monorepo/backend/domain/pb";
option objc_class_prefix = "HPA";

enum AuditlogEventType {
  AUDITLOG_EVENT_TYPE_UNKNOWN = 0;
  AUDITLOG_EVENT_TYPE_LOGIN_R_AUTOFILL = 1;
  AUDITLOG_EVENT_TYPE_LOGIN_R_PASSWORD_SHOW = 100;
  AUDITLOG_EVENT_TYPE_LOGIN_R_PASSWORD_COPY = 101;
  AUDITLOG_EVENT_TYPE_LOGIN_R_PASSWORD_INSERT_CONTEXT_MENU = 102;
  AUDITLOG_EVENT_TYPE_LOGIN_R_CUSTOM_FIELD_SHOW = 200;
  AUDITLOG_EVENT_TYPE_LOGIN_R_CUSTOM_FIELD_COPY = 201;
  AUDITLOG_EVENT_TYPE_LOGIN_R_CUSTOM_FIELD_INSERT_CONTEXT_MENU = 202;
  AUDITLOG_EVENT_TYPE_LOGIN_R_TOTP_SECRET_SHOW = 300;
  AUDITLOG_EVENT_TYPE_CREDIT_CARD_R_SECURITY_CODE_SHOW = 400;
  AUDITLOG_EVENT_TYPE_CREDIT_CARD_R_SECURITY_CODE_COPY = 401;
  AUDITLOG_EVENT_TYPE_CREDIT_CARD_R_PIN_SHOW = 402;
  AUDITLOG_EVENT_TYPE_CREDIT_CARD_R_PIN_COPY = 403;
  AUDITLOG_EVENT_TYPE_CREDIT_CARD_R_SECURITY_CODE_INSERT_CONTEXT_MENU = 404;
  AUDITLOG_EVENT_TYPE_CREDIT_CARD_R_PIN_INSERT_CONTEXT_MENU = 405;
  AUDITLOG_EVENT_TYPE_WIFI_R_QR_SHOW = 500;
  AUDITLOG_EVENT_TYPE_LOGIN_W_CREATE = 10001;
  AUDITLOG_EVENT_TYPE_LOGIN_W_CHANGE = 10002;
  AUDITLOG_EVENT_TYPE_LOGIN_W_DELETE = 10003;
  AUDITLOG_EVENT_TYPE_LOGIN_W_ARCHIVE = 10004;
  AUDITLOG_EVENT_TYPE_LOGIN_W_RESTORE_FROM_ARCHIVE = 10005;
  AUDITLOG_EVENT_TYPE_LOGIN_W_MOVE = 10006;
  AUDITLOG_EVENT_TYPE_LOGIN_SHARE_LINK_CREATE = 20001;
  AUDITLOG_EVENT_TYPE_PROFILE_CREATE = 30001;
  AUDITLOG_EVENT_TYPE_PROFILE_DELETE = 30002;
  AUDITLOG_EVENT_TYPE_PROFILE_CLAIM_WITH_START_CODE = 30003;
  AUDITLOG_EVENT_TYPE_PROFILE_DISCONNECT = 30004;
  AUDITLOG_EVENT_TYPE_PROFILE_PROMOTE_TO_ADMIN = 30005;
  AUDITLOG_EVENT_TYPE_PROFILE_DEMOTE_ADMIN = 30006;
  AUDITLOG_EVENT_TYPE_LOGIN_SHARE_SECRET_CREATE = 20002;
}

enum AuditlogEventTypeGroup {
  AUDITLOG_EVENT_TYPE_GROUP_UNKNOWN = 0;
  AUDITLOG_EVENT_TYPE_GROUP_LOGIN_MIN = 1;
  AUDITLOG_EVENT_TYPE_GROUP_LOGIN_MAX = 29999;
  AUDITLOG_EVENT_TYPE_GROUP_PROFILE_MIN = 30001;
  AUDITLOG_EVENT_TYPE_GROUP_PROFILE_MAX = 39999;
}

