syntax = "proto3";

package domain;

import "authenticator.proto";
import "profile.proto";
import "sync_update.proto";

option go_package = "gitlab.com/cotechde/monorepo/backend/domain/pb";

message ModifyAuthenticatorsRequest {
  repeated AuthenticatorCreationData create_authenticator_ops = 1;
  repeated string delete_authenticator_ids = 2;
  bytes authenticator_block = 3;
  bytes authenticator_block_signature = 4;
  repeated ProfileRegenerateData profiles = 5;
}

message ModifyAuthenticatorsResponse {
  SyncUpdate sync_update = 1;
  repeated string authenticator_ids = 2;
}

message ListAuthenticatorsRequest {
  bytes latest_authenticator_block_hash = 1;
}

message ListAuthenticatorsResponse {
  repeated Authenticator authenticators = 1;
  repeated AuthenticatorBlock authenticator_blocks = 2;
}

message CreateInitialAuthenticatorBlockRequest {
  AuthenticatorBlock authenticator_block = 1;
}

message CreateInitialAuthenticatorBlockResponse {
  SyncUpdate sync_update = 1;
}

message SetDeviceTokenRequest {
}

message SetDeviceTokenResponse {
}

service AuthenticatorService {
  rpc Modify(ModifyAuthenticatorsRequest) returns (ModifyAuthenticatorsResponse) {}
  rpc List(ListAuthenticatorsRequest) returns (ListAuthenticatorsResponse) {}
  rpc CreateInitialAuthenticatorBlock(CreateInitialAuthenticatorBlockRequest) returns (CreateInitialAuthenticatorBlockResponse) {}
  rpc SetDeviceToken(SetDeviceTokenRequest) returns (SetDeviceTokenResponse) {}
}

