syntax = "proto3";

package domain;

import "locks.proto";
import "authenticator_type.proto";
import "webauthn_prf_support_status.proto";

option go_package = "gitlab.com/cotechde/monorepo/backend/domain/pb";

message AuthenticatorData {
  message Webauthn {
    string webauthn_id = 1;
    bytes prf_salt = 2;
  }

  AuthenticatorType authenticator_type = 12;
  bytes high_security_login_sig_pub_key = 2;
  bytes high_security_identity_sig_pub_key = 3;
  bytes high_security_profile_seed_enc_pub_key = 4;
  bytes high_security_profile_seed_enc_pub_key_signature = 5;
  bytes storable_sig_pub_key = 6;
  bytes storable_sig_pub_key_signature = 7;
  bytes storable_profile_seed_enc_pub_key = 8;
  bytes storable_profile_seed_enc_pub_key_signature = 9;
  string secret_info = 10;
  bytes secret_salt = 11;
  AuthenticatorData.Webauthn webauthn = 13;
  reserved 1;
}

message AuthenticatorCreationData {
  message WebauthnAuthenticatorCreationData {
    string webauthn_id = 1;
    bytes prf_salt = 2;
    WebauthnPrfSupportStatus prf_support_status = 3;
    string register_request_id = 4;
    string response_json = 5;
  }

  AuthenticatorData data = 1;
  repeated ProfileAuthenticatorLock profile_locks = 2;
  AuthenticatorCreationData.WebauthnAuthenticatorCreationData webauthn = 3;
}

message Authenticator {
  string id = 1;
  AuthenticatorData data = 2;
}

message AuthenticatorBlock {
  bytes blob = 1;
  bytes signature = 2;
}

