syntax = "proto3";

package domain;

import "sync_update.proto";

option go_package = "gitlab.com/cotechde/monorepo/backend/domain/pb";

enum ChannelRecipient {
  CHANNEL_RECIPIENT_UNSPECIFIED = 0;
  CHANNEL_RECIPIENT_CLIENT = 1;
  CHANNEL_RECIPIENT_AUTHENTICATOR = 2;
}

message CreateChannelRequest {
  string user_id = 1;
  bytes data = 2;
  bool exposed = 3;
  string channel_type = 4;
}

message CreateChannelResponse {
  string channel_id = 1;
}

message ClaimChannelRequest {
  string channel_id = 1;
  string authenticator_id = 2;
  bytes data = 3;
}

message ClaimChannelResponse {
  bytes data = 1;
}

message ReadChannelRequest {
  string channel_id = 1;
  ChannelRecipient recipient = 2;
}

message ReadChannelResponse {
  bytes data = 1;
}

message WriteChannelRequest {
  string channel_id = 1;
  ChannelRecipient recipient = 2;
  bytes data = 3;
}

message WriteChannelResponse {
}

message DeleteChannelRequest {
  string channel_id = 1;
}

message DeleteChannelResponse {
  SyncUpdate sync_update = 1;
}

service ChannelService {
  rpc Create(CreateChannelRequest) returns (CreateChannelResponse) {}
  rpc Claim(ClaimChannelRequest) returns (ClaimChannelResponse) {}
  rpc Read(ReadChannelRequest) returns (ReadChannelResponse) {}
  rpc Write(WriteChannelRequest) returns (WriteChannelResponse) {}
  rpc Delete(DeleteChannelRequest) returns (DeleteChannelResponse) {}
}

