syntax = "proto3";

package domain;

import "google/protobuf/timestamp.proto";
import "session_type.proto";
import "sync_update.proto";
import "authenticator_type.proto";

option go_package = "gitlab.com/cotechde/monorepo/backend/domain/pb";

message Token {
  string token = 1;
  google.protobuf.Timestamp expires_at = 2;
}

message CreateChallengeRequest {
  string email = 1;
  string backup_authenticator_id = 3;
  string user_id = 4;
  reserved 2;
}

message CreateChallengeResponse {
  message Authenticator {
    message Webauthn {
      string webauthn_id = 1;
      bytes prf_salt = 2;
    }

    string id = 1;
    AuthenticatorType authenticator_type = 4;
    string secret_info = 3;
    CreateChallengeResponse.Authenticator.Webauthn webauthn = 5;
    reserved 2;
  }

  string user_id = 1;
  string challenge = 2;
  repeated CreateChallengeResponse.Authenticator authenticators = 3;
}

message CreateLongPollChannelChallengeRequest {
  string public_key_hash = 1;
}

message CreateLongPollChannelChallengeResponse {
  message Authenticator {
    string id = 1;
    AuthenticatorType authenticator_type = 4;
    string secret_info = 3;
    reserved 2;
  }

  string user_id = 1;
  string challenge = 2;
  CreateLongPollChannelChallengeResponse.Authenticator authenticator = 3;
  bytes authenticator_reply = 4;
}

message CompleteLongPollChannelRequest {
  string public_key_hash = 1;
  string authenticator_id = 2;
  bytes authenticator_reply = 3;
}

message CompleteLongPollChannelResponse {
}

message CreateTokensRequest {
  message SessionUnlock {
    bytes encrypted_secret = 1;
    google.protobuf.Timestamp expires_at = 3;
    bool single_use = 5;
  }

  string authenticator_id = 2;
  string challenge = 3;
  bytes response = 4;
  CreateTokensRequest.SessionUnlock session_unlock = 5;
  SessionType session_type = 6;
}

message CreateTokensResponse {
  Token access_token = 1;
  string session_id = 2;
  SyncUpdate sync_update = 4;
  int32 token_version = 5;
  reserved 3;
}

message CreateAuditlogWriteTokenRequest {
  string organization_id = 1;
}

message CreateAuditlogWriteTokenResponse {
  Token token = 1;
}

message CreateAuditlogAdminTokenRequest {
  string organization_id = 1;
}

message CreateAuditlogAdminTokenResponse {
  Token token = 1;
}

message CreateLFDOverridesAdminTokenRequest {
}

message CreateLFDOverridesAdminTokenResponse {
  Token token = 1;
}

message CreateSyncTokenRequest {
}

message CreateSyncTokenResponse {
  Token token = 1;
}

message RefreshTokenRequest {
}

message RefreshTokenResponse {
  Token new_access_token = 1;
  int32 token_version = 2;
}

service CredentialService {
  rpc CreateChallenge(CreateChallengeRequest) returns (CreateChallengeResponse) {}
  rpc CreateLongPollChannelChallenge(CreateLongPollChannelChallengeRequest) returns (CreateLongPollChannelChallengeResponse) {}
  rpc CompleteLongPollChannel(CompleteLongPollChannelRequest) returns (CompleteLongPollChannelResponse) {}
  rpc CreateTokens(CreateTokensRequest) returns (CreateTokensResponse) {}
  rpc CreateAuditlogWriteToken(CreateAuditlogWriteTokenRequest) returns (CreateAuditlogWriteTokenResponse) {}
  rpc CreateAuditlogAdminToken(CreateAuditlogAdminTokenRequest) returns (CreateAuditlogAdminTokenResponse) {}
  rpc CreateLFDOverridesAdminToken(CreateLFDOverridesAdminTokenRequest) returns (CreateLFDOverridesAdminTokenResponse) {}
  rpc CreateSyncToken(CreateSyncTokenRequest) returns (CreateSyncTokenResponse) {}
  rpc RefreshToken(RefreshTokenRequest) returns (RefreshTokenResponse) {}
}

