syntax = "proto3";

package domainerr;

option java_package = "app.heylogin.android.proto";
option go_package = "gitlab.com/cotechde/monorepo/backend/domain/pb";
option objc_class_prefix = "HPA";

enum ErrorGroup {
  EG_UNDEFINED = 0;
  EG_UNSPECIFIC = 10000;
  EG_ACCOUNT = 20000;
  EG_CREDENTIAL = 30000;
  EG_AUTHENTICATOR = 40000;
  EG_VAULT = 50000;
  EG_ORGANIZATION = 60000;
  EG_PROFILE = 70000;
  EG_INTEGRATION = 80000;
  EG_AUDITLOG = 90000;
  EG_WEBAUTHN = 100000;
  EG_SHARELINK = 110000;
  EG_USER_CONFIRMATION = 120000;
}

enum ErrorCode {
  UNDEFINED = 0;
  PERMISSION_DENIED = 10100;
  TIMEOUT = 10200;
  CANCELED = 10300;
  BAD_REQUEST = 10400;
  CLIENT_OUTDATED = 10426;
  INTERNAL = 10500;
  UNAVAILABLE = 10503;
  EMAIL_TAKEN = 20100;
  INVALID_EMAIL = 20101;
  EMAIL_ALREADY_VERIFIED = 20102;
  EMAIL_REQUIRED = 20103;
  INVALID_LOCALE = 20105;
  EMAIL_INVITE_NOT_ACTIVE = 20106;
  EMAIL_TAKEN_NOT_RECOVERABLE = 20107;
  MALFORMED_USER_SETTINGS = 20108;
  EMAIL_TAKEN_VERIFIED_DOMAIN = 20109;
  EMAIL_TAKEN_ORG_ADMIN_RECOVERABLE = 20110;
  USER_NOT_FOUND = 20400;
  SESSION_NOT_FOUND = 20410;
  INVALID_TIMEOUT = 20420;
  SESSION_ALREADY_UNLOCKED = 20430;
  SESSION_NOT_UNLOCKED = 20431;
  INVITATION_NOT_FOUND = 20450;
  PROFILES_LOCKED = 20451;
  INVALID_VERIFICATION_TOKEN = 20460;
  NOT_ALLOWED_FOR_USER_TYPE = 20470;
  MALFORMED_CLIENT_SETTINGS = 20480;
  MALFORMED_DEVICE_INFO = 20481;
  INVALID_UNLOCK_TIME_LIMIT = 20482;
  REGISTER_USE_LEGACY = 20500;
  MISSING_CREDENTIALS = 30100;
  INVALID_SIGNATURE = 30400;
  INVALID_CHALLENGE = 30410;
  INVALID_CREDENTIALS = 30420;
  CHALLENGE_USER_MISMATCH = 30430;
  LONG_POLL_CHANNEL_NOT_FOUND = 30440;
  LONG_POLL_CHANNEL_ALREADY_EXISTS = 30441;
  INVALID_USER_SWITCH = 30450;
  INVALID_SESSION_TYPE = 30460;
  AUTHENTICATOR_BLOCK_OUT_OF_SYNC = 40100;
  AUTHENTICATOR_NOT_FOUND = 40400;
  AUTHENTICATOR_CHANNEL_NOT_FOUND = 40410;
  AUTHENTICATOR_CHANNEL_ALREADY_CLAIMED = 40411;
  NO_AUTHENTICATOR_OPERATION = 40420;
  MISSING_AUTHENTICATOR_BLOCK = 40430;
  AUTHENTICATOR_BLOCK_NOT_FOUND = 40440;
  AUTHENTICATOR_BLOCK_EXISTS = 40450;
  INVALID_AUTHENTICATOR_TYPE = 40460;
  INVALID_RECIPIENT = 40500;
  VAULT_OUT_OF_SYNC = 50100;
  NOT_ALLOWED_FOR_VAULT = 50110;
  VAULT_INSUFFICIENT_ACCESS = 50120;
  EMPTY_COMMIT = 50200;
  VAULT_NOT_FOUND = 50400;
  CONFLICTING_VAULT_EXISTS = 50401;
  MISSING_VAULT_AUTHENTICATOR_LOCK = 50410;
  MISSING_VAULT_PROFILE_LOCK = 50411;
  MISSING_VAULT = 50420;
  INVALID_UPDATE_TIME = 50430;
  INVALID_VAULT_TYPE = 50431;
  MALFORMED_LOGIN_MAINTENANCE_CRITERIA = 50432;
  MISSING_VAULT_ADMIN = 50440;
  VAULT_DIRTY = 50450;
  MISSING_ENCRYPTED_VAULT_MESSAGE_PRIVATE_KEY = 50460;
  MISSING_VAULT_MESSAGE_PUBLIC_KEY = 50461;
  UNHANDLED_VAULT_MESSAGE = 50462;
  INVALID_VAULT_MESSAGE_TYPE = 50463;
  VAULT_MESSAGE_NOT_FOUND = 50464;
  VAULT_INBOX_SLUG_INVALID = 50470;
  VAULT_INBOX_SLUG_TAKEN = 50471;
  VAULT_MEMBER_SYNC_OUTDATED = 50472;
  ORGANIZATION_INSUEFFICIENT_ACCESS = 60100;
  NOT_ALLOWED_FOR_ORGANIZATION = 60101;
  ORGANIZATION_NOT_FOUND = 60400;
  USER_ALREADY_IN_ORGANIZATION = 60401;
  ORGANIZATION_MISSING_ADMIN = 60410;
  INVALID_ORGANIZATION_NAME = 60430;
  ORGANIZATION_INVALID_CONTACT = 60431;
  COUPON_INVALID = 60440;
  COUPON_ALREADY_REDEEMED = 60441;
  COUPON_INCOMPATIBLE = 60442;
  OTHER_PROFILE_EMAIL_CONFLICTS = 60450;
  INVALID_ORGANIZATION_DELETION_TOKEN = 60460;
  MALFORMED_PASSWORD_POLICY = 60470;
  MALFORMED_PARENT_ORGANIZATION_METADATA = 60471;
  MALFORMED_ENTRA_SETTINGS = 60472;
  LICENSE_COUNT_EXCEEDED = 60480;
  INVALID_LICENSE = 60481;
  ROLE_NOT_FOUND = 61404;
  INVALID_ROLE = 61405;
  NOT_ALLOWED_FOR_ROLE = 61406;
  PROFILE_NOT_FOUND = 70400;
  PROFILE_ALREADY_ENABLED = 70401;
  PROFILE_ALREADY_CONNECTED = 70402;
  PROFILE_STARTCODE_INACTIVE = 70403;
  MISSING_PROFILE_AUTHENTICATOR_LOCK = 70410;
  PROFILE_OUT_OF_SYNC = 70411;
  MISSING_PROFILE_PROFILE_LOCK = 70412;
  START_CODE_INVALID = 70430;
  START_CODE_BLOCKED = 70431;
  START_CODE_MISSING = 70432;
  NOT_ALLOWED_FOR_PROFILE = 70433;
  INTEGRATION_NOT_INITIALIZED = 80400;
  INTEGRATION_UNAUTHORIZED = 80401;
  INTEGRATION_USER_NOT_FOUND = 80402;
  INTEGRATION_GROUP_NOT_FOUND = 80403;
  INTEGRATION_INTERNAL = 80500;
  AUDITLOG_MALFORMED_EVENT = 90400;
  AUDITLOG_ADMIN_INVALID_CREDENTIALS = 90420;
  AUDITLOG_WRITE_INVALID_CREDENTIALS = 90421;
  AUDITLOG_SUBMISSION_ERROR = 90500;
  WEBAUTHN_VALIDATE_ERROR = 100400;
  WEBAUTHN_DATA_ERROR = 100401;
  WEBAUTHN_REQUEST_NOT_FOUND = 100402;
  WEBAUTHN_INVALID_TRANSPORT = 100403;
  MISSING_WEBAUTHN_CREDENTIAL = 100404;
  MISSING_WEBAUTHN_RESPONSE = 100405;
  WEBAUTHN_MISSING_USER_VERIFICATION = 100406;
  SHARE_LINK_NOT_FOUND = 110400;
  USER_CONFIRMATION_NOT_FOUND = 120400;
}

