syntax = "proto3";

package domain;

import "sync_update.proto";
import "google/protobuf/timestamp.proto";

option go_package = "gitlab.com/cotechde/monorepo/backend/domain/pb";

message EntraGetAuthorizeUriRequest {
  string organization_id = 1;
  string redirect_uri = 2;
}

message EntraGetAuthorizeUriResponse {
  string uri = 1;
}

message EntraFinishAuthorizationRequest {
  string result_query_string = 1;
}

message EntraFinishAuthorizationResponse {
  SyncUpdate sync_update = 1;
  string organization_id = 2;
}

message EntraGetTenantRequest {
  string organization_id = 1;
  bool force_refresh = 2;
}

message EntraGetTenantResponse {
  message User {
    string entra_user_id = 1;
    string email = 2;
    repeated string member_of = 3;
    bool matches_sync_filter = 4;
    bool account_enabled = 5;
  }

  message Group {
    string entra_group_id = 1;
    string name = 2;
  }

  google.protobuf.Timestamp synchronized_at = 1;
  repeated EntraGetTenantResponse.User users = 2;
  repeated EntraGetTenantResponse.Group groups = 3;
  bool is_unauthorized = 4;
}

message EntraClearAuthorizationRequest {
  string organization_id = 1;
}

message EntraClearAuthorizationResponse {
  SyncUpdate sync_update = 1;
}

message EntraGetSyncOperationsRequest {
  string organization_id = 1;
}

message EntraSetSettingsRequest {
  string organization_id = 1;
  string entra_settings = 15;
}

message EntraSetSettingsResponse {
  SyncUpdate sync_update = 1;
}

message EntraGetSyncOperationsResponse {
  message CreateProfileOperation {
    string entra_user_id = 1;
    string email = 2;
    string role_id = 3;
  }

  repeated EntraGetSyncOperationsResponse.CreateProfileOperation create_profiles = 1;
}

message CsvSetIntegrationDataRequest {
  string organization_id = 1;
  string data_json = 2;
}

message CsvSetIntegrationDataResponse {
  SyncUpdate sync_update = 1;
}

message CsvGetIntegrationDataRequest {
  string organization_id = 1;
}

message CsvGetIntegrationDataResponse {
  string data_json = 1;
}

message GWorkspaceGetAuthorizeUriRequest {
  string organization_id = 1;
  string redirect_uri = 2;
}

message GWorkspaceGetAuthorizeUriResponse {
  string uri = 1;
}

message GWorkspaceFinishAuthorizationRequest {
  string result_query_string = 1;
}

message GWorkspaceFinishAuthorizationResponse {
  SyncUpdate sync_update = 1;
  string organization_id = 2;
}

message GWorkspaceClearAuthorizationRequest {
  string organization_id = 1;
}

message GWorkspaceClearAuthorizationResponse {
  SyncUpdate sync_update = 1;
}

message GWorkspaceListRequest {
  string organization_id = 1;
  bool force_refresh = 2;
}

message GWorkspaceListResponse {
  message User {
    string id = 1;
    string email = 2;
  }

  google.protobuf.Timestamp updated_at = 1;
  repeated GWorkspaceListResponse.User users = 2;
}

service IntegrationsService {
  rpc EntraGetAuthorizeUri(EntraGetAuthorizeUriRequest) returns (EntraGetAuthorizeUriResponse) {}
  rpc EntraFinishAuthorization(EntraFinishAuthorizationRequest) returns (EntraFinishAuthorizationResponse) {}
  rpc EntraGetTenant(EntraGetTenantRequest) returns (EntraGetTenantResponse) {}
  rpc EntraClearAuthorization(EntraClearAuthorizationRequest) returns (EntraClearAuthorizationResponse) {}
  rpc EntraGetSyncOperations(EntraGetSyncOperationsRequest) returns (EntraGetSyncOperationsResponse) {}
  rpc EntraSetSettings(EntraSetSettingsRequest) returns (EntraSetSettingsResponse) {}
  rpc CsvSetIntegrationData(CsvSetIntegrationDataRequest) returns (CsvSetIntegrationDataResponse) {}
  rpc CsvGetIntegrationData(CsvGetIntegrationDataRequest) returns (CsvGetIntegrationDataResponse) {}
  rpc GWorkspaceGetAuthorizeUri(GWorkspaceGetAuthorizeUriRequest) returns (GWorkspaceGetAuthorizeUriResponse) {}
  rpc GWorkspaceFinishAuthorization(GWorkspaceFinishAuthorizationRequest) returns (GWorkspaceFinishAuthorizationResponse) {}
  rpc GWorkspaceClearAuthorization(GWorkspaceClearAuthorizationRequest) returns (GWorkspaceClearAuthorizationResponse) {}
  rpc GWorkspaceList(GWorkspaceListRequest) returns (GWorkspaceListResponse) {}
}

