syntax = "proto3";

package domain;

import "google/protobuf/timestamp.proto";

option go_package = "gitlab.com/cotechde/monorepo/backend/domain/pb";

message ReplaceLFDOverridesRequest {
  repeated string override_json = 1;
}

message ReplaceLFDOverridesResponse {
}

message DeleteLFDOverridesRequest {
  repeated string override_ids = 1;
}

message DeleteLFDOverridesResponse {
}

message ListLFDOverridesRequest {
  google.protobuf.Timestamp last_known_overrides_update_time = 1;
}

message ListLFDOverridesResponse {
  google.protobuf.Timestamp overrides_update_time = 1;
  repeated string overrides_json = 2;
}

service LFDOverridesService {
  rpc Replace(ReplaceLFDOverridesRequest) returns (ReplaceLFDOverridesResponse) {}
  rpc Delete(DeleteLFDOverridesRequest) returns (DeleteLFDOverridesResponse) {}
  rpc List(ListLFDOverridesRequest) returns (ListLFDOverridesResponse) {}
}

