syntax = "proto3";

package domain;

option go_package = "gitlab.com/cotechde/monorepo/backend/domain/pb";

enum LicenseType {
  LICENSE_TYPE_UNKNOWN = 0;
  LICENSE_TYPE_NONE = 1;
  LICENSE_TYPE_COUPON_APPSUMO = 2;
  LICENSE_TYPE_PADDLE = 3;
  LICENSE_TYPE_NONPROFIT = 4;
  LICENSE_TYPE_CONTRACT = 5;
  LICENSE_TYPE_CUSTOM = 6;
  LICENSE_TYPE_VIA_MSP = 7;
  LICENSE_TYPE_EXAMPLE = 8;
  LICENSE_TYPE_COUPON_PRIME_CLUB = 9;
  LICENSE_TYPE_COUPON_FAMILY = 10;
  LICENSE_TYPE_VIA_DISTRIBUTOR = 11;
  LICENSE_TYPE_DIRECT_RESELLER = 12;
}

