syntax = "proto3";

package domain;

import "google/protobuf/timestamp.proto";

option go_package = "gitlab.com/cotechde/monorepo/backend/domain/pb";

enum LoginMaintenanceCriteriaVersion {
  LOGIN_MAINTENANCE_CRITERIA_VERSION_UNKNOWN = 0;
  LOGIN_MAINTENANCE_CRITERIA_VERSION_V3 = 3;
}

message LoginMaintenanceCriteria {
  bool no_login = 1;
  google.protobuf.Timestamp leaked_passwords_min_change_time = 2;
  int32 login_summary_min_version = 3;
  google.protobuf.Timestamp password_policy_min_change_time = 4;
}

