syntax = "proto3";

package domain;

option go_package = "gitlab.com/cotechde/monorepo/backend/domain/pb";

enum MaintenanceTask {
  MAINTENANCE_TASK_UNKNOWN = 0;
  MAINTENANCE_TASK_ORGANIZATION_PRELIMINARY_PROFILES_V3 = 12;
  MAINTENANCE_TASK_PROCESS_VAULT_MESSAGES_V2 = 11;
  MAINTENANCE_TASK_ENABLE_PRF_OPPORTUNISTICALLY_V1 = 14;
  MAINTENANCE_TASK_ORGANIZATION_PERFORM_MAINTENANCE_IF_DISABLED_V1 = 18;
  MAINTENANCE_TASK_ORGANIZATION_ENTRA_SYNC_V2 = 29;
  MAINTENANCE_TASK_LEAKED_PASSWORD_CHECK_V2 = 27;
  MAINTENANCE_TASK_TEAM_SYNC_MEMBERS_V1 = 22;
  MAINTENANCE_TASK_TEAM_SYNC_MEMBERS_BACKEND_V2 = 30;
  MAINTENANCE_TASK_CREATE_DELEGATED_ADMINS_VAULT_V2 = 31;
  MAINTENANCE_TASK_LOGIN_SUMMARY_V1 = 24;
  MAINTENANCE_TASK_PASSWORD_POLICY_CHECK_V2 = 28;
  reserved 1;
  reserved 2;
  reserved 3;
  reserved 9;
  reserved 17;
  reserved 4;
  reserved 5;
  reserved 10;
  reserved 13;
  reserved 15;
  reserved 6;
  reserved 7;
  reserved 8;
  reserved 16;
  reserved 19;
  reserved 20;
  reserved 21;
  reserved 25;
  reserved 23;
  reserved 26;
}

