syntax = "proto3";

package domain;

import "google/protobuf/timestamp.proto";
import "sync_update.proto";
import "vault_service.proto";
import "profile.proto";
import "unlock_time_limit.proto";
import "locks.proto";
import "google/protobuf/wrappers.proto";
import "subscription_plan.proto";
import "role.proto";

option go_package = "gitlab.com/cotechde/monorepo/backend/domain/pb";

message SubscriptionStatus {
  message PaddleActive {
    string base_url = 1;
    google.protobuf.Timestamp next_bill_date = 2;
    int32 free_members = 3;
    string email = 4;
  }

  message PaddlePastDue {
    string base_url = 1;
    google.protobuf.Timestamp next_bill_date = 2;
    int32 free_members = 3;
  }

  message PaddlePausedDelinquent {
    string base_url = 1;
    google.protobuf.Timestamp paused_at = 2;
    google.protobuf.Timestamp paused_from = 3;
    int32 free_members = 4;
  }

  message PaddlePausedVoluntary {
    string base_url = 1;
    google.protobuf.Timestamp paused_at = 2;
    google.protobuf.Timestamp paused_from = 3;
    int32 free_members = 4;
  }

  message PaddleDeleted {
    google.protobuf.Timestamp cancellation_effective_date = 1;
    int32 free_members = 2;
  }

  message Trial {
    google.protobuf.Timestamp trial_end_date = 1;
  }

  message ActiveFree {
    int32 free_members = 1;
  }

  message Custom {
    string left = 1;
    string right = 2;
  }

  message Example {
    string left = 1;
    string right = 2;
  }


  oneof status {
    SubscriptionStatus.PaddleActive status_paddle_active = 1;
    SubscriptionStatus.PaddlePastDue status_paddle_past_due = 2;
    SubscriptionStatus.PaddlePausedDelinquent status_paddle_paused_delinquent = 3;
    SubscriptionStatus.PaddlePausedVoluntary status_paddle_paused_voluntary = 4;
    SubscriptionStatus.PaddleDeleted status_paddle_deleted = 5;
    SubscriptionStatus.Trial status_trial = 6;
    SubscriptionStatus.Custom status_custom = 7;
    SubscriptionStatus.ActiveFree status_active_free = 8;
    SubscriptionStatus.Example status_example = 9;
  }
}

message CreateOrganizationRequest {
  message ParentOrganizationInfo {
    string id = 1;
    ProfileProfileLock downstream_admin_profile_lock = 2;
  }

  string name = 1;
  string icon = 2;
  string email = 17;
  string domain = 24;
  ProfileData user_profile = 16;
  ProfileData admin_profile = 21;
  VaultCreationData admin_vault_data = 23;
  VaultCreationData login_summary_vault_data = 25;
  VaultCreationData personal_vault_data = 7;
  bytes personal_vault_superuser_encrypted_storable_vault_key = 8;
  bytes personal_vault_superuser_encrypted_high_security_vault_key = 9;
  bytes personal_vault_superuser_encrypted_vault_message_private_key = 18;
  VaultPairCreationData team_vault_data = 10;
  bytes team_vault_superuser_encrypted_storable_vault_key = 11;
  bytes team_vault_superuser_encrypted_high_security_vault_key = 12;
  bytes team_vault_superuser_encrypted_vault_message_private_key = 19;
  bytes team_associated_vault_superuser_encrypted_storable_vault_key = 13;
  bytes team_associated_vault_superuser_encrypted_high_security_vault_key = 14;
  bytes team_associated_vault_superuser_encrypted_vault_message_private_key = 20;
  string contact_json = 15;
  CreateOrganizationRequest.ParentOrganizationInfo parent_organization_info = 22;
  reserved 3;
  reserved 5;
  reserved 6;
  reserved 4;
}

message CreateOrganizationResponse {
  SyncUpdate sync_update = 1;
  string organization_id = 2;
  string super_user_id = 3;
  string authenticator_id = 4;
  string personal_vault_id = 6;
  string team_vault_id = 7;
  string team_associated_vault_id = 8;
  string profile_id = 9;
  string admin_profile_id = 10;
  string admin_vault_id = 11;
  string login_summary_vault_id = 12;
  reserved 5;
}

message UpdateOrganizationRequest {
  message StringArray {
    repeated string value = 1;
  }

  message ExportPermissionValue {
    ExportPermission value = 1;
  }

  string organization_id = 1;
  google.protobuf.StringValue name = 2;
  google.protobuf.StringValue icon = 3;
  google.protobuf.BoolValue restrict_create_team = 4;
  google.protobuf.BoolValue auditlog_enable = 5;
  google.protobuf.BoolValue child_organization_management_enable = 11;
  google.protobuf.BoolValue restrict_personal_logins = 8;
  UpdateOrganizationRequest.StringArray monitored_domains = 7;
  google.protobuf.StringValue password_policy = 9;
  UnlockTimeLimit unlock_time_limit = 10;
  google.protobuf.StringValue client_settings = 12;
  google.protobuf.StringValue share_link_sender_email = 13;
  google.protobuf.BoolValue entra_prefer_user_principal_name = 14;
  google.protobuf.BoolValue role_management_enable = 16;
  UpdateOrganizationRequest.ExportPermissionValue user_role_export_permission = 17;
  reserved 6;
  reserved 15;
}

message UpdateOrganizationResponse {
  SyncUpdate sync_update = 1;
}

message ModifyMembersRequest {
  message CreateProfileOperation {
    VaultCreationData personal_vault_data = 3;
    ProfileData profile = 4;
    ProfileProfileLock admin_profile_lock = 9;
    string email = 6;
    bool create_start_code_and_send_mail = 8;
    bool set_start_code_email_sender = 11;
    string entra_user_id = 10;
    string role_id = 12;
    reserved 1;
    reserved 2;
    reserved 7;
    reserved 5;
  }

  message UpdateProfileOperation {
    string profile_id = 1;
    ProfileProfileLock admin_profile_lock = 4;
    google.protobuf.StringValue role_id = 6;
    reserved 2;
    reserved 5;
    reserved 3;
  }

  string organization_id = 1;
  repeated ModifyMembersRequest.CreateProfileOperation create_profile_ops = 7;
  repeated ModifyMembersRequest.UpdateProfileOperation update_profile_ops = 8;
  repeated string delete_profile_ids = 9;
  reserved 2;
  reserved 3;
  reserved 4;
  reserved 5;
  reserved 10;
}

message ModifyMembersResponse {
  SyncUpdate sync_update = 1;
  repeated string personal_vault_ids = 2;
}

message CreateServiceProfileRequest {
  string organization_id = 1;
  ProfileData profile = 2;
  ProfileProfileLock downstream_admin_profile_lock = 3;
}

message CreateServiceProfileResponse {
  SyncUpdate sync_update = 1;
  string profile_id = 2;
}

message LeaveOrganizationRequest {
  string organization_id = 1;
}

message LeaveOrganizationResponse {
  SyncUpdate sync_update = 1;
}

message AcceptInviteRequest {
  string organization_id = 1;
}

message AcceptInviteResponse {
  SyncUpdate sync_update = 1;
}

message RedeemCouponRequest {
  string organization_id = 1;
  string coupon_text = 2;
}

message RedeemCouponResponse {
  SyncUpdate sync_update = 1;
}

message DeleteOrganizationRequest {
  string organization_id = 1;
}

message DeleteOrganizationResponse {
  SyncUpdate sync_update = 1;
}

message GetSubscriptionDetailsRequest {
  string organization_id = 1;
}

message GetSubscriptionDetailsResponse {
  message Payment {
    google.protobuf.Timestamp event_time = 1;
    string receipt_url = 2;
    int64 sale_gross_cents = 3;
    int64 payment_tax_cents = 4;
    string currency = 5;
    string order_id = 6;
  }

  message PaddleSubscription {
    SubscriptionPlan plan = 1;
    int32 quantity = 2;
    int32 unit_price_cents = 3;
    int32 total_price_cents = 4;
    string currency = 5;
    google.protobuf.Timestamp next_bill_date = 6;
  }

  repeated GetSubscriptionDetailsResponse.Payment payments = 1;
  GetSubscriptionDetailsResponse.PaddleSubscription paddle_subscription = 4;
  SubscriptionStatus status = 5;
  int32 billable_users = 6;
  reserved 2;
  reserved 3;
}

message RequestAdditionalLicensesRequest {
  string organization_id = 1;
  int32 additional_license_count = 2;
  string message = 3;
}

message RequestAdditionalLicensesResponse {
}

message RegenerateOrganizationProfileRequest {
  string organization_id = 1;
  ProfileRegenerateData profile = 2;
  repeated ProfileRegenerateData child_organization_profiles = 4;
  string user_id = 3;
}

message RegenerateOrganizationProfileResponse {
  SyncUpdate sync_update = 1;
}

message ClaimPreliminaryProfileRequest {
  string profile_id = 1;
}

message ClaimPreliminaryProfileResponse {
  SyncUpdate sync_update = 1;
}

message RegenerateAdminProfileRequest {
  string organization_id = 1;
  ProfileRegenerateData profile = 2;
}

message RegenerateAdminProfileResponse {
  SyncUpdate sync_update = 1;
  string admin_profile_id = 2;
  string admin_profile_key_generation_id = 3;
}

message RenewProfileStartCodeRequest {
  string organization_id = 1;
  repeated string profile_ids = 2;
}

message RenewProfileStartCodeResponse {
  SyncUpdate sync_update = 1;
}

message SendStartCodeEmailRequest {
  string organization_id = 1;
  repeated string profile_ids = 2;
}

message SendStartCodeEmailResponse {
  SyncUpdate sync_update = 1;
}

message RevokeProfileStartCodeRequest {
  string organization_id = 1;
  repeated string profile_ids = 2;
}

message RevokeProfileStartCodeResponse {
  SyncUpdate sync_update = 1;
}

message GetOrganizationDeletionInfoRequest {
  string organization_id = 1;
  string token = 2;
}

message GetOrganizationDeletionInfoResponse {
  string organization_name = 1;
  string requested_by_email = 2;
  int32 user_count = 3;
  google.protobuf.Timestamp requested_at = 4;
}

message DeleteOrganizationWithTokenRequest {
  string organization_id = 1;
  string token = 2;
}

message DeleteOrganizationWithTokenResponse {
}

message RemoveOrganizationDeletionTokenRequest {
  string organization_id = 1;
  string token = 2;
}

message RemoveOrganizationDeletionTokenResponse {
}

message GetBreachDataRequest {
  string organization_id = 1;
}

message GetBreachDataResponse {
  message BreachModel {
    string name = 1;
    string title = 2;
    google.protobuf.Timestamp breach_date = 3;
    google.protobuf.Timestamp added_date = 4;
    repeated string data_classes = 5;
    string logo_path = 6;
  }

  message Breach {
    GetBreachDataResponse.BreachModel model = 1;
    repeated string aliases = 2;
  }

  message MonitoredDomain {
    string domain = 1;
    repeated GetBreachDataResponse.Breach breaches = 2;
  }

  repeated GetBreachDataResponse.MonitoredDomain domains = 1;
  google.protobuf.Timestamp last_check_date = 2;
  float total_pwn_count_billions = 3;
  int32 total_breach_count = 4;
}

message ListLocksForProfileRegenerateRequest {
  string organization_id = 1;
  string profile_id = 2;
}

message ListLocksForProfileRegenerateResponse {
  message Vault {
    string id = 1;
    string generation_id = 2;
    VaultProfileLock admin_vault_profile_lock = 3;
  }

  message ChildOrganization {
    string id = 1;
    string profile_id = 2;
    SyncUpdateProfile admin_profile = 3;
    repeated ListLocksForProfileRegenerateResponse.Vault vaults = 4;
  }

  repeated ListLocksForProfileRegenerateResponse.Vault vaults = 1;
  repeated ListLocksForProfileRegenerateResponse.ChildOrganization child_organizations = 2;
}

message CreateLoginSummaryVaultRequest {
  string organization_id = 1;
  VaultCreationData login_summary_vault_data = 2;
}

message CreateLoginSummaryVaultResponse {
  SyncUpdate sync_update = 1;
  string login_summary_vault_id = 2;
}

message AddRoleRequest {
  string organization_id = 1;
  string custom_name = 2;
  RolePermissions permissions = 3;
}

message AddRoleResponse {
  string role_id = 1;
  SyncUpdate sync_update = 2;
}

message UpdateRoleRequest {
  string organization_id = 1;
  string role_id = 2;
  google.protobuf.StringValue custom_name = 3;
  RolePermissions permissions = 4;
  repeated ProfileProfileLock new_admin_profile_profile_locks = 5;
}

message UpdateRoleResponse {
  SyncUpdate sync_update = 1;
}

message DeleteRoleRequest {
  string organization_id = 1;
  string role_id = 2;
}

message DeleteRoleResponse {
  SyncUpdate sync_update = 1;
}

service OrganizationService {
  rpc Create(CreateOrganizationRequest) returns (CreateOrganizationResponse) {}
  rpc Update(UpdateOrganizationRequest) returns (UpdateOrganizationResponse) {}
  rpc ModifyMembers(ModifyMembersRequest) returns (ModifyMembersResponse) {}
  rpc CreateServiceProfile(CreateServiceProfileRequest) returns (CreateServiceProfileResponse) {}
  rpc Leave(LeaveOrganizationRequest) returns (LeaveOrganizationResponse) {}
  rpc AcceptInvite(AcceptInviteRequest) returns (AcceptInviteResponse) {}
  rpc RedeemCoupon(RedeemCouponRequest) returns (RedeemCouponResponse) {}
  rpc Delete(DeleteOrganizationRequest) returns (DeleteOrganizationResponse) {}
  rpc GetSubscriptionDetails(GetSubscriptionDetailsRequest) returns (GetSubscriptionDetailsResponse) {}
  rpc RequestAdditionalLicenses(RequestAdditionalLicensesRequest) returns (RequestAdditionalLicensesResponse) {}
  rpc RegenerateOrganizationProfile(RegenerateOrganizationProfileRequest) returns (RegenerateOrganizationProfileResponse) {}
  rpc RegenerateAdminProfile(RegenerateAdminProfileRequest) returns (RegenerateAdminProfileResponse) {}
  rpc RenewProfileStartCode(RenewProfileStartCodeRequest) returns (RenewProfileStartCodeResponse) {}
  rpc SendStartCodeEmail(SendStartCodeEmailRequest) returns (SendStartCodeEmailResponse) {}
  rpc RevokeProfileStartCode(RevokeProfileStartCodeRequest) returns (RevokeProfileStartCodeResponse) {}
  rpc GetDeletionInfo(GetOrganizationDeletionInfoRequest) returns (GetOrganizationDeletionInfoResponse) {}
  rpc DeleteWithToken(DeleteOrganizationWithTokenRequest) returns (DeleteOrganizationWithTokenResponse) {}
  rpc RemoveDeletionToken(RemoveOrganizationDeletionTokenRequest) returns (RemoveOrganizationDeletionTokenResponse) {}
  rpc GetBreachData(GetBreachDataRequest) returns (GetBreachDataResponse) {}
  rpc ListLocksForProfileRegenerate(ListLocksForProfileRegenerateRequest) returns (ListLocksForProfileRegenerateResponse) {}
  rpc CreateLoginSummaryVault(CreateLoginSummaryVaultRequest) returns (CreateLoginSummaryVaultResponse) {}
  rpc AddRole(AddRoleRequest) returns (AddRoleResponse) {}
  rpc UpdateRole(UpdateRoleRequest) returns (UpdateRoleResponse) {}
  rpc DeleteRole(DeleteRoleRequest) returns (DeleteRoleResponse) {}
}

