syntax = "proto3";

package domain;

import "profile.proto";
import "vault_service.proto";
import "sync_update.proto";

option go_package = "gitlab.com/cotechde/monorepo/backend/domain/pb";

message CreatePrivateProfileRequest {
  string email = 1;
  ProfileData private_profile = 2;
  VaultCreationData private_vault = 3;
}

message CreatePrivateProfileResponse {
  SyncUpdate sync_update = 1;
  string private_profile_id = 2;
  string private_vault_id = 3;
}

message DeletePrivateProfileRequest {
  string private_profile_id = 1;
}

message DeletePrivateProfileResponse {
  SyncUpdate sync_update = 1;
}

message RegenerateProfilesRequest {
  repeated ProfileRegenerateData profiles = 1;
}

message RegenerateProfilesResponse {
  SyncUpdate sync_update = 1;
}

message ListProfilesRequest {
  repeated string profile_ids = 1;
}

message ListProfilesResponse {
  repeated ForeignProfile profiles = 1;
}

message ProfileRequestEmailChangeRequest {
  string profile_id = 1;
  string email = 2;
}

message ProfileRequestEmailChangeResponse {
  SyncUpdate sync_update = 1;
  bool verification_email_sent = 2;
}

message ProfileCancelEmailChangeRequest {
  string profile_id = 1;
}

message ProfileCancelEmailChangeResponse {
  SyncUpdate sync_update = 1;
}

message VerifyEmailAddressRequest {
  string token = 1;
}

message VerifyEmailAddressResponse {
  string email = 1;
}

message ClaimWithStartCodeRequest {
  string start_code = 2;
  string profile_id = 3;
  reserved 1;
}

message ClaimWithStartCodeResponse {
  SyncUpdate sync_update = 1;
  string organization_id = 2;
}

message GetProfileInfoRequest {
  string profile_id = 1;
}

message GetProfileInfoResponse {
  string email = 1;
  string organization_id = 4;
  string organization_name = 2;
  string organization_icon = 3;
}

message CheckProfileStartCodeRequest {
  string email = 1;
  string profile_id = 3;
  string start_code = 2;
}

message CheckProfileStartCodeResponse {
}

service ProfileService {
  rpc CreatePrivate(CreatePrivateProfileRequest) returns (CreatePrivateProfileResponse) {}
  rpc DeletePrivate(DeletePrivateProfileRequest) returns (DeletePrivateProfileResponse) {}
  rpc Regenerate(RegenerateProfilesRequest) returns (RegenerateProfilesResponse) {}
  rpc List(ListProfilesRequest) returns (ListProfilesResponse) {}
  rpc RequestEmailChange(ProfileRequestEmailChangeRequest) returns (ProfileRequestEmailChangeResponse) {}
  rpc CancelEmailChange(ProfileCancelEmailChangeRequest) returns (ProfileCancelEmailChangeResponse) {}
  rpc VerifyEmailAddress(VerifyEmailAddressRequest) returns (VerifyEmailAddressResponse) {}
  rpc ClaimWithStartCode(ClaimWithStartCodeRequest) returns (ClaimWithStartCodeResponse) {}
  rpc GetProfileInfo(GetProfileInfoRequest) returns (GetProfileInfoResponse) {}
  rpc CheckStartCode(CheckProfileStartCodeRequest) returns (CheckProfileStartCodeResponse) {}
}

