syntax = "proto3";

package domain;

import "locks.proto";
import "profile_type.proto";

option go_package = "gitlab.com/cotechde/monorepo/backend/domain/pb";

message ProfileData {
  string id = 1;
  ProfileType profile_type = 15;
  string key_generation_id = 2;
  bytes high_security_identity_sig_pub_key = 3;
  bytes high_security_vault_key_enc_pub_key = 4;
  bytes high_security_vault_key_enc_pub_key_signature = 5;
  bytes high_security_profile_seed_enc_pub_key = 6;
  bytes high_security_profile_seed_enc_pub_key_signature = 7;
  bytes storable_sig_pub_key = 8;
  bytes storable_sig_pub_key_signature = 9;
  bytes storable_vault_key_enc_pub_key = 10;
  bytes storable_vault_key_enc_pub_key_signature = 11;
  bytes storable_profile_seed_enc_pub_key = 12;
  bytes storable_profile_seed_enc_pub_key_signature = 13;
  repeated ProfileAuthenticatorLock authenticator_locks = 14;
  repeated ProfileProfileLock upstream_profile_locks = 16;
}

message ForeignProfile {
  string id = 1;
  string key_generation_id = 2;
  ProfileType profile_type = 3;
  string organization_id = 4;
  bytes high_security_identity_sig_pub_key = 5;
  bytes high_security_vault_key_enc_pub_key = 6;
  bytes high_security_vault_key_enc_pub_key_signature = 7;
  bytes high_security_profile_seed_enc_pub_key = 8;
  bytes high_security_profile_seed_enc_pub_key_signature = 9;
  bytes storable_sig_pub_key = 10;
  bytes storable_sig_pub_key_signature = 11;
  bytes storable_vault_key_enc_pub_key = 12;
  bytes storable_vault_key_enc_pub_key_signature = 13;
  bytes storable_profile_seed_enc_pub_key = 14;
  bytes storable_profile_seed_enc_pub_key_signature = 15;
  string email = 16;
}

message ProfileRegenerateData {
  ProfileData profile = 1;
  repeated VaultLockCreationData vault_locks = 2;
  repeated ProfileProfileLock downstream_profile_locks = 3;
}

