syntax = "proto3";

package domain;

option java_package = "app.heylogin.android.proto";
option go_package = "gitlab.com/cotechde/monorepo/backend/domain/pb";
option objc_class_prefix = "HPA";

enum RegistrationInfoStatus {
  REGISTRATION_INFO_STATUS_UNKNOWN = 0;
  REGISTRATION_INFO_STATUS_AVAILABLE_FREE = 1;
  REGISTRATION_INFO_STATUS_AVAILABLE_START_CODE_REQUIRED = 2;
  REGISTRATION_INFO_STATUS_UNAVAILABLE_RESERVED_VERIFIED_DOMAIN = 3;
  REGISTRATION_INFO_STATUS_UNAVAILABLE_RECOVER_VIA_BACKUP_CODE = 4;
  REGISTRATION_INFO_STATUS_UNAVAILABLE_RECOVER_VIA_ADMIN = 5;
  REGISTRATION_INFO_STATUS_UNAVAILABLE_RECOVER_VIA_BACKUP_CODE_OR_ADMIN = 6;
  REGISTRATION_INFO_STATUS_UNAVAILABLE_ADMIN_ACTION_REQUIRED = 7;
  REGISTRATION_INFO_STATUS_UNAVAILABLE_NOT_RECOVERABLE = 8;
}

