syntax = "proto3";

package domain;

import "google/protobuf/timestamp.proto";
import "role_type.proto";
import "vault_permission_level.proto";

option go_package = "gitlab.com/cotechde/monorepo/backend/domain/pb";

enum ExportPermission {
  EXPORT_PERMISSION_NONE = 0;
  EXPORT_PERMISSION_PERSONAL_VAULT = 1;
  EXPORT_PERMISSION_ACCESSIBLE_VAULTS = 2;
  EXPORT_PERMISSION_ADMIN_ALL_ORGANIZATION_TEAMS = 3;
}

enum ChildOrganizationAccess {
  CHILD_ORGANIZATION_ACCESS_NONE = 0;
  CHILD_ORGANIZATION_ACCESS_LIST = 1;
  CHILD_ORGANIZATION_ACCESS_ADMIN_MANAGE = 2;
}

enum MaximumAssignableVaultPermission {
  MAXIMUM_ASSIGNABLE_VAULT_PERMISSION_NONE = 0;
  MAXIMUM_ASSIGNABLE_VAULT_PERMISSION_READ_ONLY = 1;
  MAXIMUM_ASSIGNABLE_VAULT_PERMISSION_READ_WRITE = 2;
  MAXIMUM_ASSIGNABLE_VAULT_PERMISSION_ADMIN = 3;
}

message RolePermissions {
  MaximumAssignableVaultPermission admin_can_assign_team_permission_other = 12;
  MaximumAssignableVaultPermission admin_can_assign_team_permission_self = 13;
  bool admin_can_change_settings = 4;
  bool admin_can_manage_organization = 1;
  bool admin_can_view_foreign_personal_vaults = 11;
  ExportPermission export_vaults = 3;
  ChildOrganizationAccess child_organization_access = 9;
  bool can_access_personal_vault = 8;
  bool can_change_plan = 6;
  bool can_connect_users = 14;
  bool can_create_child_organizations = 10;
  bool can_create_teams = 2;
  bool can_view_auditlog = 5;
  bool can_view_monitoring = 7;
  bool can_view_users = 15;
}

message Role {
  string id = 1;
  RoleType role_type = 2;
  string custom_name = 3;
  bool is_privileged = 4;
  RolePermissions permissions = 6;
  google.protobuf.Timestamp changed_at = 7;
  reserved 5;
}

