syntax = "proto3";

package domain;

option go_package = "gitlab.com/cotechde/monorepo/backend/domain/pb";

message PreviewShareLinkRequest {
  string share_link_id = 1;
}

message PreviewShareLinkResponse {
  bytes encrypted_payload = 1;
  string sender_email = 2;
  string organization_name = 3;
}

message ShowShareLinkRequest {
  string share_link_id = 1;
}

message ShowShareLinkResponse {
  bytes encrypted_payload = 1;
  bytes encrypted_protected_secret = 2;
  string sender_email = 3;
  string organization_name = 4;
}

service ShareLinkService {
  rpc Preview(PreviewShareLinkRequest) returns (PreviewShareLinkResponse) {}
  rpc Show(ShowShareLinkRequest) returns (ShowShareLinkResponse) {}
}

