syntax = "proto3";

package domain;

import "user_confirmation_data.proto";
import "user_confirmation_result_type.proto";
import "sync_update.proto";

option go_package = "gitlab.com/cotechde/monorepo/backend/domain/pb";

message CreateUserConfirmationRequest {
  UserConfirmationData data = 1;
}

message CreateUserConfirmationResponse {
  SyncUpdate sync_update = 1;
  string id = 2;
  string webauthn_options_json = 3;
}

message GetUserConfirmationRequest {
  string id = 1;
}

message GetUserConfirmationResponse {
  string requesting_session_id = 1;
  UserConfirmationData data = 2;
  string fallback_string = 3;
}

message SendUserConfirmationResultRequest {
  string id = 1;
  UserConfirmationResultType type = 2;
  string webauthn_response_json = 3;
}

message SendUserConfirmationResultResponse {
  SyncUpdate sync_update = 1;
}

message RetrieveUserConfirmationResultRequest {
  string id = 1;
}

message RetrieveUserConfirmationResultResponse {
  UserConfirmationResultType result_type = 1;
}

message CancelUserConfirmationRequest {
  string id = 1;
}

message CancelUserConfirmationResponse {
  SyncUpdate sync_update = 1;
}

service UserConfirmationService {
  rpc Create(CreateUserConfirmationRequest) returns (CreateUserConfirmationResponse) {}
  rpc Get(GetUserConfirmationRequest) returns (GetUserConfirmationResponse) {}
  rpc SendResult(SendUserConfirmationResultRequest) returns (SendUserConfirmationResultResponse) {}
  rpc RetrieveResult(RetrieveUserConfirmationResultRequest) returns (RetrieveUserConfirmationResultResponse) {}
  rpc Cancel(CancelUserConfirmationRequest) returns (CancelUserConfirmationResponse) {}
}

