syntax = "proto3";

package domain;

option java_package = "app.heylogin.android.proto";
option go_package = "gitlab.com/cotechde/monorepo/backend/domain/pb";
option objc_class_prefix = "HPA";

enum UserConfirmationType {
  USER_CONFIRMATION_TYPE_UNKNOWN = 0;
  USER_CONFIRMATION_TYPE_DEBUG = 1;
  USER_CONFIRMATION_TYPE_USER_EXPORT_VAULT = 10001;
  USER_CONFIRMATION_TYPE_USER_EXPORT_ALL = 10002;
  USER_CONFIRMATION_TYPE_USER_EXPORT_ORG_ALL_TEAMS = 10003;
  USER_CONFIRMATION_TYPE_USER_EXPORT_ORG_MEMBER_TEAMS = 10004;
  USER_CONFIRMATION_TYPE_USER_SHOW_BACKUP_CODE = 10010;
  USER_CONFIRMATION_TYPE_USER_REGENERATE_BACKUP_CODE = 10011;
  USER_CONFIRMATION_TYPE_USER_ADD_CREDENTIAL_SECURITY_KEY = 10020;
  USER_CONFIRMATION_TYPE_USER_ADD_CREDENTIAL_WINDOWS_HELLO = 10021;
  USER_CONFIRMATION_TYPE_USER_ADD_CREDENTIAL_TOUCH_ID = 10022;
  USER_CONFIRMATION_TYPE_ORG_ADMIN_DELETE_ORG = 30000;
  USER_CONFIRMATION_TYPE_ORG_ADMIN_CONVERT_CHILD_ORG_TO_INDEPENDENT = 30002;
}

