syntax = "proto3";

package domain;

import "sync_update.proto";
import "locks.proto";
import "vault_member_sync_mode.proto";
import "vault_message_type.proto";
import "vault_permission_level.proto";
import "login_maintenance_criteria.proto";
import "google/protobuf/wrappers.proto";
import "google/protobuf/timestamp.proto";

option go_package = "gitlab.com/cotechde/monorepo/backend/domain/pb";

message UpdateMessage {
  string vault_id = 1;
  string generation_id = 2;
  VaultMessageType type = 3;
  bytes encrypted_data = 4;
}

message VaultRegenerateData {
  message RegeneratedMessage {
    string id = 1;
    bytes encrypted_data = 2;
  }

  string id = 1;
  string latest_commit_id = 2;
  repeated VaultProfileLock profile_locks = 7;
  bytes squashed_commits = 5;
  bytes message_public_key = 8;
  repeated string delete_message_ids = 9;
  repeated VaultRegenerateData.RegeneratedMessage regenerated_messages = 11;
  reserved 3;
  reserved 4;
  reserved 10;
  reserved 6;
}

message VaultCreationData {
  bytes first_commit_blob = 1;
  VaultProfileLock profile_lock = 4;
  string organization_id = 3;
  bytes message_public_key = 5;
  VaultProfileLock admin_profile_lock = 6;
  reserved 2;
}

message VaultPairCreationData {
  bytes first_commit_blob = 1;
  VaultProfileLock profile_lock = 7;
  bytes message_public_key = 9;
  VaultProfileLock admin_profile_lock = 11;
  bytes associated_first_commit_blob = 4;
  VaultProfileLock associated_profile_lock = 8;
  bytes associated_message_public_key = 10;
  VaultProfileLock associated_admin_profile_lock = 12;
  string organization_id = 6;
  reserved 2;
  reserved 5;
}

message ShareSecretUpdate {
  string id = 1;
  bytes encrypted_payload = 2;
}

message ShareSecretsDelete {
  repeated string keep_share_secret_ids = 1;
}

message ShareLinkUpdate {
  string id = 1;
  bytes encrypted_payload = 2;
  bytes encrypted_protected_secret = 3;
}

message ShareLinksDelete {
  repeated string keep_share_link_ids = 1;
}

message CreateCommitRequest {
  string vault_id = 1;
  string latest_commit_id = 2;
  bytes new_commit_blob = 3;
  google.protobuf.Timestamp update_time = 4;
  repeated string delete_message_ids = 7;
  repeated UpdateMessage update_messages = 8;
  repeated ShareLinkUpdate share_link_updates = 9;
  ShareLinksDelete delete_share_links = 10;
  repeated ShareSecretUpdate share_secret_updates = 12;
  ShareSecretsDelete delete_share_secrets = 13;
  LoginMaintenanceCriteria login_maintenance_criteria = 14;
  reserved 5;
  reserved 6;
  reserved 11;
}

message CreateCommitResponse {
  string commit_id = 1;
  repeated string update_message_ids = 2;
}

message CreateGenerationRequest {
  VaultRegenerateData vault = 1;
  repeated UpdateMessage update_messages = 2;
  ShareLinksDelete delete_share_links = 3;
  repeated ShareLinkUpdate share_link_updates = 4;
  ShareSecretsDelete delete_share_secrets = 5;
  repeated ShareSecretUpdate share_secret_updates = 6;
  LoginMaintenanceCriteria login_maintenance_criteria = 14;
}

message CreateGenerationResponse {
  string commit_id = 1;
  string generation_id = 2;
  SyncUpdate sync_update = 3;
  repeated string update_message_ids = 4;
}

message ListCommitsRequest {
  string vault_id = 1;
  google.protobuf.StringValue latest_commit_id = 2;
  google.protobuf.StringValue latest_first_commit_id = 4;
  bool force_locks = 3;
}

message ListCommitsResponse {
  message Commit {
    string id = 1;
    bytes blob = 2;
  }

  message Message {
    string id = 1;
    VaultMessageType type = 2;
    bytes encrypted_data = 3;
    string sender_vault_id = 4;
    bytes backend_message = 5;
  }

  string current_generation_id = 1;
  repeated ListCommitsResponse.Commit newer_commits = 2;
  VaultProfileLock profile_lock = 6;
  VaultProfileLock admin_profile_lock = 8;
  google.protobuf.Timestamp server_time = 4;
  string first_commit_id = 5;
  repeated ListCommitsResponse.Message messages = 7;
  LoginMaintenanceCriteria login_maintenance_criteria = 9;
  reserved 3;
}

message CreateTeamRequest {
  VaultPairCreationData creation_data = 1;
  VaultMemberSyncMode member_sync_mode = 2;
  string entra_group_id = 3;
}

message CreateTeamResponse {
  string vault_id = 1;
  string associated_vault_id = 3;
  SyncUpdate sync_update = 2;
}

message DeleteTeamRequest {
  string vault_id = 1;
}

message DeleteTeamResponse {
  SyncUpdate sync_update = 1;
}

message UpdateVaultRequest {
  message VaultMemberSyncModeValue {
    VaultMemberSyncMode value = 1;
  }

  string vault_id = 1;
  UpdateVaultRequest.VaultMemberSyncModeValue member_sync_mode = 2;
}

message UpdateVaultResponse {
  SyncUpdate sync_update = 1;
}

message ModifyTeamUsersRequest {
  message AddProfileOperation {
    string profile_id = 1;
    VaultProfileLock lock = 2;
    VaultProfileLock associated_lock = 3;
  }

  string vault_id = 1;
  repeated ModifyTeamUsersRequest.AddProfileOperation add_profile_ops = 11;
  repeated string remove_profile_ids = 12;
  VaultRegenerateData regenerate_data = 4;
  VaultRegenerateData associated_regenerate_data = 5;
  google.protobuf.Timestamp update_time = 6;
  string assoc_latest_commit_id = 7;
  bytes assoc_new_commit_blob = 8;
  string generation_id = 9;
  string assoc_generation_id = 10;
  google.protobuf.Timestamp member_sync_time = 13;
  reserved 2;
  reserved 3;
}

message ModifyTeamUsersResponse {
  SyncUpdate sync_update = 1;
}

message CreateInboxVaultRequest {
  VaultPairCreationData creation_data = 1;
  string metadata = 3;
  reserved 2;
}

message CreateInboxVaultResponse {
  string vault_id = 1;
  string associated_vault_id = 3;
  SyncUpdate sync_update = 2;
}

message UpdateInboxRequest {
  string vault_id = 1;
  google.protobuf.StringValue metadata = 3;
  google.protobuf.BoolValue enabled = 5;
  reserved 2;
  reserved 4;
}

message UpdateInboxResponse {
  SyncUpdate sync_update = 1;
}

message DeleteInboxVaultRequest {
  string vault_id = 1;
}

message DeleteInboxVaultResponse {
  SyncUpdate sync_update = 1;
}

message ListMessagePublicKeysRequest {
  string organization_id = 1;
  repeated string vault_ids = 2;
}

message ListMessagePublicKeysResponse {
  message MessagePublicKey {
    string vault_id = 1;
    string generation_id = 2;
    bytes key = 3;
  }

  repeated ListMessagePublicKeysResponse.MessagePublicKey message_public_keys = 1;
}

message GetVaultSyncMemberTargetStateRequest {
  string vault_id = 1;
}

message GetVaultSyncMemberTargetStateResponse {
  message Member {
    string profile_id = 1;
    VaultPermissionLevel default_permission = 2;
    repeated VaultPermissionLevel allowed_permissions = 3;
  }

  repeated GetVaultSyncMemberTargetStateResponse.Member members = 1;
  google.protobuf.Timestamp sync_time = 2;
  string vault_name = 3;
}

service VaultService {
  rpc CreateCommit(CreateCommitRequest) returns (CreateCommitResponse) {}
  rpc CreateGeneration(CreateGenerationRequest) returns (CreateGenerationResponse) {}
  rpc ListCommits(ListCommitsRequest) returns (ListCommitsResponse) {}
  rpc CreateTeam(CreateTeamRequest) returns (CreateTeamResponse) {}
  rpc DeleteTeam(DeleteTeamRequest) returns (DeleteTeamResponse) {}
  rpc Update(UpdateVaultRequest) returns (UpdateVaultResponse) {}
  rpc ModifyTeamUsers(ModifyTeamUsersRequest) returns (ModifyTeamUsersResponse) {}
  rpc CreateInboxVault(CreateInboxVaultRequest) returns (CreateInboxVaultResponse) {}
  rpc UpdateInbox(UpdateInboxRequest) returns (UpdateInboxResponse) {}
  rpc DeleteInboxVault(DeleteInboxVaultRequest) returns (DeleteInboxVaultResponse) {}
  rpc ListMessagePublicKeys(ListMessagePublicKeysRequest) returns (ListMessagePublicKeysResponse) {}
  rpc GetSyncMemberTargetState(GetVaultSyncMemberTargetStateRequest) returns (GetVaultSyncMemberTargetStateResponse) {}
}

