syntax = "proto3";

package domain;

import "google/protobuf/timestamp.proto";
import "sync_update.proto";
import "credential_type.proto";
import "webauthn_prf_support_status.proto";

option go_package = "gitlab.com/cotechde/monorepo/backend/domain/pb";

message RegisterCredentialInitRequest {
  CredentialType credential_type = 1;
}

message RegisterCredentialInitResponse {
  string request_id = 1;
  string options_json = 2;
}

message RegisterCredentialForAccountCreationInitRequest {
  string email = 1;
}

message RegisterCredentialForAccountCreationInitResponse {
  string request_id = 1;
  string options_json = 2;
}

message RegisterCredentialFinishRequest {
  string request_id = 1;
  string response_json = 2;
  WebauthnPrfSupportStatus prf_support_status = 3;
}

message RegisterCredentialFinishResponse {
  SyncUpdate sync_update = 1;
}

message UnlockSessionInitRequest {
}

message UnlockSessionInitResponse {
  string request_id = 1;
  string options_json = 2;
}

message UnlockSessionFinishRequest {
  string request_id = 1;
  string response_json = 2;
  google.protobuf.Timestamp max_expires_at = 3;
}

message UnlockSessionFinishResponse {
  SyncUpdate sync_update = 1;
}

message DeleteCredentialsRequest {
  repeated string webauthn_ids = 1;
}

message DeleteCredentialsResponse {
  SyncUpdate sync_update = 1;
}

service WebauthnService {
  rpc RegisterCredentialInit(RegisterCredentialInitRequest) returns (RegisterCredentialInitResponse) {}
  rpc RegisterCredentialForAccountCreationInit(RegisterCredentialForAccountCreationInitRequest) returns (RegisterCredentialForAccountCreationInitResponse) {}
  rpc RegisterCredentialFinish(RegisterCredentialFinishRequest) returns (RegisterCredentialFinishResponse) {}
  rpc UnlockSessionInit(UnlockSessionInitRequest) returns (UnlockSessionInitResponse) {}
  rpc UnlockSessionFinish(UnlockSessionFinishRequest) returns (UnlockSessionFinishResponse) {}
  rpc DeleteCredentials(DeleteCredentialsRequest) returns (DeleteCredentialsResponse) {}
}

