//! One `#[test]` per scenario file.
//!
//! `rerun-if-changed` on the directory is the point: cargo re-runs this when a
//! file appears, so a new recording becomes a test with no second edit. A
//! proc-macro reading the same directory could not promise that — `tracked_path`
//! is nightly-only, so an added file may not trigger re-expansion, which is the
//! precise failure this exists to prevent.

use std::{env, fmt::Write as _, fs, path::PathBuf};

fn main() {
    let dir = PathBuf::from("tests/scenarios");
    println!("cargo:rerun-if-changed={}", dir.display());
    println!("cargo:rerun-if-changed=build.rs");

    let out = PathBuf::from(env::var("OUT_DIR").expect("cargo sets OUT_DIR")).join("scenarios.rs");

    // This script runs for every target of the crate, including a release
    // build of the binary, and the directory is absent from a packaged crate.
    // Emitting an empty module is the whole of the handling that needs.
    let mut names: Vec<String> = fs::read_dir(&dir)
        .into_iter()
        .flatten()
        .flatten()
        .map(|entry| entry.path())
        .filter(|path| path.extension().is_some_and(|e| e == "json"))
        .filter_map(|path| {
            path.file_stem()
                .map(|stem| stem.to_string_lossy().into_owned())
        })
        .collect();
    names.sort();

    let mut body = String::from("// @generated by heyl-cli/build.rs. Do not edit.\n\n");
    body.push_str("mod scenario {\n    use super::harness;\n\n");
    for name in &names {
        // `expired-unlock.json` is `scenario::expired_unlock`; the file keeps
        // the hyphen because it is a name, not an identifier.
        let ident = name.replace(['-', '.', ' '], "_");
        let _ = write!(
            body,
            "    #[test]\n    fn {ident}() {{\n        harness::run({name:?});\n    }}\n\n"
        );
    }
    body.push_str("}\n");

    fs::write(&out, body).expect("the generated tests are writable");
}
